// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/penggehero/funny-im/app/im_server/domain/server"
	"github.com/penggehero/funny-im/app/im_server/domain/service"
)

// Injectors from wire.go:

func newIMServer() *server.ImServer {
	engine := gin.New()
	imService := service.NewIMService()
	imServer := server.NewImServer(engine, imService)
	return imServer
}
